### ISSUE TITLE
How would you return the url of the image to dropzone template along with  toastr.success?

### ISSUE THREAD

**Issue by ghost** [riebeekn/photo-blog#1]
Sorry to bother you but I can't find a way to return the url.

**Comment by riebeekn** [comment]
Hi Noah, the issue is that it takes a bit of time for the image to upload so until it does so a URL is not available.  You would probably need to use a timeout if you wanted to get the URL from within the .Insert, so in dropzone.js you would do something like:

``` javascript
    Images.insert(newFile, function (error, fileObj) {
        if (error) {
              toastr.error("Upload failed... please try again.");
        } else {
          Meteor.setTimeout(function() {
            if (fileObj.isUploaded()) {
              console.log(fileObj.url());
            }
          }, 2000);
          toastr.success('Upload succeeded!');
        }
      });
```

Hope that helps!

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
sorry to bother you again but that returns a error 

```
http-call-client.js:101 The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
```

**Comment by riebeekn** [comment]
That's a warning message, but doesn't affect the upload, see https://github.com/CollectionFS/Meteor-CollectionFS/issues/688

I uploaded a new branch (console-log-out-the-image-url-on-upload) that contains the code in dropzone.js that prints the URL to the browser console.  So if you grab that branch you can see it in action, hopefully that helps!

**Comment by ghost** [comment]
thanks
